on:
  push:
    branches:
      - haxelib-version

jobs:
  haxelib_submit:
    name: Publish to Haxelib
    runs-on: ubuntu-latest
    environment: my-secrets
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6
      - uses: edgarrc/action-7z@v1
        with:
          args: 7z a reflaxe.zip newproject/* src/* LICENSE Run.hx extraParams.hxml haxelib.json
      - run: |
          haxe -version
          haxelib submit reflaxe.zip ${{ secrets.HAXELIB_PASSWORD }} -debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
